theme = "hugo-book"
baseURL = 'http://loafabreadly.github.io/'
languageCode = 'en-us'
title = 'The Snurka Notes Repo'
enableGitInfo = true
disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'dark'
  BookToC = true
  BookLogo = 'logo.png'
  BookRepo = 'https://github.com/Loafabreadly/notes'
  BookCommitPath = 'commit'
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1  

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github Repo"
  url = "https://github.com/Loafabreadly/notes"
  weight = 10

  